/**
 * Quick Email Draft Modal
 *
 * Simple modal for drafting physician notifications from clinical events.
 * Uses template-based generation (no AI) and mailto for immediate sending.
 */

import { useState, useEffect } from 'react';
import type {
  KeywordMatch,
  DetectedClinicalEvent,
  ClinicalEventType,
  TriggerPriority,
} from '../../types/clinicalEvents.types';
import {
  EVENT_TYPE_CONFIG,
  PRIORITY_CONFIG,
} from '../../types/clinicalEvents.types';

interface QuickEmailDraftModalProps {
  event: KeywordMatch | DetectedClinicalEvent | null;
  isOpen: boolean;
  onClose: () => void;
  patientName?: string;
  physicianName?: string;
  physicianEmail?: string;
  clinicianName?: string;
  clinicianCredentials?: string;
  agencyName?: string;
  agencyPhone?: string;
}

// Type guard to check if event is a saved DetectedClinicalEvent
function isSavedEvent(
  event: KeywordMatch | DetectedClinicalEvent
): event is DetectedClinicalEvent {
  return 'id' in event && 'createdAt' in event;
}

/**
 * Generate email subject from event
 */
function generateSubject(
  event: KeywordMatch | DetectedClinicalEvent,
  patientName: string
): string {
  const eventConfig = EVENT_TYPE_CONFIG[event.eventType as ClinicalEventType];

  const urgencyPrefix =
    event.priority === 'CRITICAL'
      ? 'URGENT: '
      : event.priority === 'HIGH'
      ? 'Important: '
      : '';

  return `${urgencyPrefix}${eventConfig?.label || event.eventType} - ${patientName}`;
}

/**
 * Generate email body from event using templates
 */
function generateBody(
  event: KeywordMatch | DetectedClinicalEvent,
  patientName: string,
  physicianName: string,
  clinicianName: string,
  clinicianCredentials: string,
  agencyName: string,
  agencyPhone: string
): string {
  const eventConfig = EVENT_TYPE_CONFIG[event.eventType as ClinicalEventType];
  const priorityConfig = PRIORITY_CONFIG[event.priority as TriggerPriority];
  const isSaved = isSavedEvent(event);

  const eventSummary = isSaved
    ? event.eventSummary
    : `${eventConfig?.label || event.eventType} detected`;

  const sourceText = isSaved
    ? event.sourceText
    : (event as KeywordMatch).sourceText;

  const detectionInfo = isSaved
    ? event.aiReasoning || `Matched keywords: ${event.matchedKeywords?.join(', ') || 'N/A'}`
    : `Matched keywords: ${(event as KeywordMatch).matchedKeywords?.join(', ') || 'N/A'}`;

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `Dear Dr. ${physicianName},

I am writing to notify you of a clinical finding for your patient, ${patientName}.

EVENT TYPE: ${eventConfig?.label || event.eventType}
PRIORITY: ${priorityConfig?.label || event.priority}
DATE: ${today}

CLINICAL FINDING:
${eventSummary}

DOCUMENTATION:
"${sourceText || 'No additional documentation available.'}"

${detectionInfo ? `ANALYSIS:\n${detectionInfo}\n` : ''}
Please advise on any changes to the plan of care.

Respectfully,

${clinicianName}${clinicianCredentials ? `, ${clinicianCredentials}` : ''}
${agencyName}
${agencyPhone}

---
This notification was generated by ${agencyName}'s clinical documentation system.
Please respond to this notification or contact us at ${agencyPhone}.`;
}

/**
 * Generate mailto URL
 */
function generateMailtoUrl(
  to: string,
  subject: string,
  body: string,
  cc?: string
): string {
  const params = new URLSearchParams();
  params.set('subject', subject);
  params.set('body', body);
  if (cc) {
    params.set('cc', cc);
  }
  return `mailto:${encodeURIComponent(to)}?${params.toString()}`;
}

export function QuickEmailDraftModal({
  event,
  isOpen,
  onClose,
  patientName = 'Patient',
  physicianName = 'Physician',
  physicianEmail = '',
  clinicianName = 'Home Health Clinician',
  clinicianCredentials = 'RN',
  agencyName = 'Home Health Agency',
  agencyPhone = '(555) 123-4567',
}: QuickEmailDraftModalProps) {
  const [toEmail, setToEmail] = useState(physicianEmail);
  const [ccEmail, setCcEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);

  // Generate draft when event changes
  useEffect(() => {
    if (event && isOpen) {
      setToEmail(physicianEmail);
      setSubject(generateSubject(event, patientName));
      setBody(
        generateBody(
          event,
          patientName,
          physicianName,
          clinicianName,
          clinicianCredentials,
          agencyName,
          agencyPhone
        )
      );
      setSendSuccess(false);
    }
  }, [
    event,
    isOpen,
    patientName,
    physicianName,
    physicianEmail,
    clinicianName,
    clinicianCredentials,
    agencyName,
    agencyPhone,
  ]);

  const handleOpenInMailApp = () => {
    if (!toEmail) {
      alert('Please enter a recipient email address');
      return;
    }

    setIsSending(true);

    // Generate and open mailto URL
    const mailtoUrl = generateMailtoUrl(toEmail, subject, body, ccEmail);
    window.open(mailtoUrl, '_blank');

    // Log for compliance (could call backend here)
    console.log('[QuickEmailDraft] Opened mailto for:', {
      to: toEmail,
      subject,
      eventType: event?.eventType,
    });

    setSendSuccess(true);
    setIsSending(false);

    // Close after a short delay
    setTimeout(() => {
      onClose();
    }, 1500);
  };

  if (!isOpen || !event) {
    return null;
  }

  const eventConfig = EVENT_TYPE_CONFIG[event.eventType as ClinicalEventType];
  const priorityConfig = PRIORITY_CONFIG[event.priority as TriggerPriority];

  return (
    <div className="fixed inset-0 z-[60] overflow-y-auto">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black bg-opacity-50 transition-opacity"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="relative bg-white rounded-xl shadow-xl max-w-3xl w-full max-h-[90vh] overflow-hidden flex flex-col">
          {/* Header */}
          <div
            className={`px-6 py-4 border-b ${priorityConfig?.bgColor || 'bg-gray-50'}`}
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="text-2xl">{eventConfig?.icon || '📧'}</span>
                <div>
                  <h2 className="text-lg font-semibold text-gray-900">
                    Draft Physician Notification
                  </h2>
                  <p className="text-sm text-gray-600">
                    {eventConfig?.label || event.eventType} - {patientName}
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="text-gray-400 hover:text-gray-600 p-1"
              >
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6 space-y-4">
            {/* PHI Warning */}
            <div className="flex items-start gap-3 p-3 bg-amber-50 border border-amber-200 rounded-lg">
              <svg className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
              <div>
                <p className="text-sm font-medium text-amber-800">PHI Notice</p>
                <p className="text-xs text-amber-700">
                  This message contains Protected Health Information. Ensure you are
                  sending to an authorized recipient.
                </p>
              </div>
            </div>

            {/* To Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                To
              </label>
              <input
                type="email"
                value={toEmail}
                onChange={(e) => setToEmail(e.target.value)}
                placeholder="physician@clinic.com"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            {/* CC Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                CC (optional)
              </label>
              <input
                type="email"
                value={ccEmail}
                onChange={(e) => setCcEmail(e.target.value)}
                placeholder="supervisor@agency.com"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            {/* Subject Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Subject
              </label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            {/* Body Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Message
              </label>
              <textarea
                value={body}
                onChange={(e) => setBody(e.target.value)}
                rows={12}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono text-sm"
              />
            </div>

            {/* Success Message */}
            {sendSuccess && (
              <div className="flex items-center gap-2 p-3 bg-green-50 border border-green-200 rounded-lg">
                <svg className="w-5 h-5 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <p className="text-sm text-green-800">
                  Opening your email client...
                </p>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="px-6 py-4 bg-gray-50 border-t flex items-center justify-between">
            <p className="text-xs text-gray-500">
              This will open your default email application
            </p>
            <div className="flex items-center gap-3">
              <button
                onClick={onClose}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={handleOpenInMailApp}
                disabled={isSending || sendSuccess || !toEmail}
                className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {isSending ? (
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                ) : (
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                  </svg>
                )}
                Open in Mail App
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default QuickEmailDraftModal;
