/**
 * Physician Email Utilities
 *
 * Generate and open mailto links for physician notifications.
 * One-click opens the user's email client with everything pre-filled.
 */

import type {
  KeywordMatch,
  DetectedClinicalEvent,
  ClinicalEventType,
  TriggerPriority,
} from '../types/clinicalEvents.types';
import {
  EVENT_TYPE_CONFIG,
  PRIORITY_CONFIG,
} from '../types/clinicalEvents.types';

// Type guard to check if event is a saved DetectedClinicalEvent
function isSavedEvent(
  event: KeywordMatch | DetectedClinicalEvent
): event is DetectedClinicalEvent {
  return 'id' in event && 'createdAt' in event;
}

/**
 * Generate email subject from event
 */
function generateSubject(
  event: KeywordMatch | DetectedClinicalEvent,
  patientName: string
): string {
  const eventConfig = EVENT_TYPE_CONFIG[event.eventType as ClinicalEventType];

  const urgencyPrefix =
    event.priority === 'CRITICAL'
      ? 'URGENT: '
      : event.priority === 'HIGH'
      ? 'Important: '
      : '';

  return `${urgencyPrefix}${eventConfig?.label || event.eventType} - ${patientName}`;
}

/**
 * Strip "Dr." prefix if already present to avoid "Dear Dr. Dr. Smith"
 */
function stripDrPrefix(name: string): string {
  return name.replace(/^Dr\.?\s*/i, '').trim();
}

/**
 * Generate email body from event using templates
 */
function generateBody(
  event: KeywordMatch | DetectedClinicalEvent,
  patientName: string,
  physicianName: string,
  clinicianName: string,
  clinicianCredentials: string,
  agencyName: string,
  agencyPhone: string
): string {
  const eventConfig = EVENT_TYPE_CONFIG[event.eventType as ClinicalEventType];
  const priorityConfig = PRIORITY_CONFIG[event.priority as TriggerPriority];
  const isSaved = isSavedEvent(event);

  // Strip any existing "Dr." prefix to avoid "Dear Dr. Dr. Smith"
  const cleanPhysicianName = stripDrPrefix(physicianName);

  const eventSummary = isSaved
    ? event.eventSummary
    : `${eventConfig?.label || event.eventType} detected`;

  const sourceText = isSaved
    ? event.sourceText
    : (event as KeywordMatch).sourceText;

  const detectionInfo = isSaved
    ? event.aiReasoning || `Matched keywords: ${event.matchedKeywords?.join(', ') || 'N/A'}`
    : `Matched keywords: ${(event as KeywordMatch).matchedKeywords?.join(', ') || 'N/A'}`;

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Build body with explicit line array to ensure proper newlines
  const lines = [
    `Dear Dr. ${cleanPhysicianName},`,
    '',
    `I am writing to notify you of a clinical finding for your patient, ${patientName}.`,
    '',
    `EVENT TYPE: ${eventConfig?.label || event.eventType}`,
    `PRIORITY: ${priorityConfig?.label || event.priority}`,
    `DATE: ${today}`,
    '',
    'CLINICAL FINDING:',
    eventSummary,
    '',
    'DOCUMENTATION:',
    `"${sourceText || 'No additional documentation available.'}"`,
    '',
  ];

  if (detectionInfo) {
    lines.push('ANALYSIS:', detectionInfo, '');
  }

  lines.push(
    'Please advise on any changes to the plan of care.',
    '',
    'Respectfully,',
    '',
    `${clinicianName}${clinicianCredentials ? `, ${clinicianCredentials}` : ''}`,
    agencyName,
    agencyPhone,
    '',
    '---',
    `This notification was generated by ${agencyName}'s clinical documentation system.`,
    `Please respond to this notification or contact us at ${agencyPhone}.`
  );

  return lines.join('\n');
}

/**
 * Generate mailto URL with proper newline encoding
 * Note: URLSearchParams encodes \n as + which doesn't work for mailto
 * We use encodeURIComponent which correctly encodes \n as %0A
 */
function generateMailtoUrl(
  to: string,
  subject: string,
  body: string
): string {
  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);
  const encodedTo = encodeURIComponent(to);
  return `mailto:${encodedTo}?subject=${encodedSubject}&body=${encodedBody}`;
}

export interface OpenPhysicianEmailOptions {
  event: KeywordMatch | DetectedClinicalEvent;
  patientName?: string;
  physicianName?: string;
  physicianEmail?: string;
  clinicianName?: string;
  clinicianCredentials?: string;
  agencyName?: string;
  agencyPhone?: string;
}

/**
 * Open email client with pre-filled physician notification.
 * One click - directly opens Outlook/Apple Mail/Gmail with everything ready.
 */
export function openPhysicianEmail({
  event,
  patientName = 'Patient',
  physicianName = 'Physician',
  physicianEmail = '',
  clinicianName = 'Home Health Clinician',
  clinicianCredentials = 'RN',
  agencyName = 'Home Health Agency',
  agencyPhone = '(555) 123-4567',
}: OpenPhysicianEmailOptions): void {
  const subject = generateSubject(event, patientName);
  const body = generateBody(
    event,
    patientName,
    physicianName,
    clinicianName,
    clinicianCredentials,
    agencyName,
    agencyPhone
  );

  const mailtoUrl = generateMailtoUrl(physicianEmail, subject, body);

  // Open mailto URL - this opens the user's default email client
  window.location.href = mailtoUrl;

  // Log for compliance/debugging
  console.log('[PhysicianEmail] Opened mailto for:', {
    to: physicianEmail,
    subject,
    eventType: event.eventType,
    priority: event.priority,
  });
}
